const AllImages = {
  // Add images like this
  Logo: require("../assets/images/logo.svg").default,
  CloseIcon: require("../assets/images/closeIcon.svg").default,
  HomePage: require("../assets/images/home/home-img.png"),
  HomePageBg1: require("../assets/images/home/HomePageBg1.jpg"),
  HomePageBg2: require("../assets/images/home/HomePageBg2.jpg"),
  HomePageBg3: require("../assets/images/home/HomePageBg3.jpg"),
  HomePageBg4: require("../assets/images/home/HomePageBg4.jpg"),
  HomePageBg5: require("../assets/images/home/HomePageBg5.jpg"),
  HomePageBg6: require("../assets/images/home/HomePageBg6.jpg"),
  HomePageBg7: require("../assets/images/home/HomePageBg6.jpg"),
  Equipment1: require("../assets/images/equipment1.png"),
  openingRestaurant: require("../assets/images/openingRestaurant.webp"),
  marketplace: require("../assets/images/marketplace.jpeg"),
  mixer: require("../assets/images/equipement/mixer.jpg"),
  slicer: require("../assets/images/equipement/slicer.jpg"),
  refrigerator: require("../assets/images/equipement/refrigerator.jpg"),
  ovens: require("../assets/images/equipement/ovens.jpg"),
  prepStations: require("../assets/images/equipement/prepStations.jpg"),
  Sinks: require("../assets/images/equipement/Sinks.jpg"),
  IceCreammachines: require("../assets/images/equipement/IceCreammachines.jpeg"),
  fork: require("../assets/images/equipement/fork.jpg"),
  dishwashers: require("../assets/images/equipement/dishwasherss.jpg"),
};
export default AllImages;
